before_script:
  - psql -c 'create database simple_sumo_backend_test;' -U postgres

language: ruby
rvm:
  - 2.7.1
  
before_install:
  - gem install bundler

services:
 - postgresql

script:
  - rspec spec -f NyanCatMusicFormatter